//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bosco.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLAssemblyTypeSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLAssemblyTypeSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bosco.SQL.SQLAssemblyTypeSetting", typeof(SQLAssemblyTypeSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AccountingPeriodSQL,Bosco.SQL.
        /// </summary>
        internal static string AccountingPeriod {
            get {
                return ResourceManager.GetString("AccountingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AddressBookSQL,Bosco.SQL.
        /// </summary>
        internal static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AmendmentSQL,Bosco.SQL.
        /// </summary>
        internal static string Amendments {
            get {
                return ResourceManager.GetString("Amendments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetClassSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetClass {
            get {
                return ResourceManager.GetString("AssetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetItemSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetItem {
            get {
                return ResourceManager.GetString("AssetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AssetUnitOfMeasureSQL,Bosco.SQL.
        /// </summary>
        internal static string AssetUnitofMeasure {
            get {
                return ResourceManager.GetString("AssetUnitofMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.AuditInfoSQL,Bosco.SQL.
        /// </summary>
        internal static string AuditInfo {
            get {
                return ResourceManager.GetString("AuditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BankSQL,Bosco.SQL.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BranchLocationSQL,Bosco.SQL.
        /// </summary>
        internal static string BranchLocation {
            get {
                return ResourceManager.GetString("BranchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BranchOfficeSQL,Bosco.SQL.
        /// </summary>
        internal static string BranchOffice {
            get {
                return ResourceManager.GetString("BranchOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BudgetSQL,Bosco.SQL.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.GeneralateSQL,Bosco.SQL.
        /// </summary>
        internal static string CongregationLedger {
            get {
                return ResourceManager.GetString("CongregationLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CongregationLedgerMappingSQL,Bosco.SQL.
        /// </summary>
        internal static string CongregationMapping {
            get {
                return ResourceManager.GetString("CongregationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.GeneralateOpeningBalanceSQL,Bosco.SQL.
        /// </summary>
        internal static string CongregationOpeningBalance {
            get {
                return ResourceManager.GetString("CongregationOpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CostCentreSQL,Bosco.SQL.
        /// </summary>
        internal static string CostCentre {
            get {
                return ResourceManager.GetString("CostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CountrySQL,Bosco.SQL.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DeducteeTypeSQL,Bosco.SQL.
        /// </summary>
        internal static string DeducteeType {
            get {
                return ResourceManager.GetString("DeducteeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.DonorAuditorSQL,Bosco.SQL.
        /// </summary>
        internal static string DonorAuditor {
            get {
                return ResourceManager.GetString("DonorAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ExecutiveMemberSQL,Bosco.SQL.
        /// </summary>
        internal static string ExecutiveMembers {
            get {
                return ResourceManager.GetString("ExecutiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FDAccountSQL,Bosco.SQL.
        /// </summary>
        internal static string FDAccount {
            get {
                return ResourceManager.GetString("FDAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FDRenewalSQL,Bosco.SQL.
        /// </summary>
        internal static string FDRenewal {
            get {
                return ResourceManager.GetString("FDRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.FixedDepositSQL,Bosco.SQL.
        /// </summary>
        internal static string FixedDeposit {
            get {
                return ResourceManager.GetString("FixedDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.HeadOfficeSQL,Bosco.SQL.
        /// </summary>
        internal static string HeadOffice {
            get {
                return ResourceManager.GetString("HeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InKindArticleSQL,Bosco.SQL.
        /// </summary>
        internal static string InKindArticle {
            get {
                return ResourceManager.GetString("InKindArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.InKindReceivedSQL,Bosco.SQL.
        /// </summary>
        internal static string InKindReceived {
            get {
                return ResourceManager.GetString("InKindReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerBank {
            get {
                return ResourceManager.GetString("LedgerBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerGroupSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerGroup {
            get {
                return ResourceManager.GetString("LedgerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LedgerProfileSQL,Bosco.SQL.
        /// </summary>
        internal static string LedgerProfile {
            get {
                return ResourceManager.GetString("LedgerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LegalEntitySQL,Bosco.SQL.
        /// </summary>
        internal static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LicenseSQL,Bosco.SQL.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.LockVoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string LockVoucher {
            get {
                return ResourceManager.GetString("LockVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ManageSecuritySQL,Bosco.SQL.
        /// </summary>
        internal static string ManageSecurity {
            get {
                return ResourceManager.GetString("ManageSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.MappingSQL,Bosco.SQL.
        /// </summary>
        internal static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.MasterRightsSQL,Bosco.SQL.
        /// </summary>
        internal static string MasterRights {
            get {
                return ResourceManager.GetString("MasterRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.CostCentreMasterSQL,Bosco.SQL.
        /// </summary>
        internal static string MasterTransactionCostCentre {
            get {
                return ResourceManager.GetString("MasterTransactionCostCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.NatureofPaymentSQL,Bosco.SQL.
        /// </summary>
        internal static string NatureofPayments {
            get {
                return ResourceManager.GetString("NatureofPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ProjectSQL,Bosco.SQL.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.ProjectCatogory,Bosco.SQL.
        /// </summary>
        internal static string ProjectCatogory {
            get {
                return ResourceManager.GetString("ProjectCatogory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.PurposeSQL,Bosco.SQL.
        /// </summary>
        internal static string Purposes {
            get {
                return ResourceManager.GetString("Purposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.RightsSQL,Bosco.SQL.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.SettingSQL,Bosco.SQL.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.SoftwareSQL,Bosco.SQL.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TDSSQL,Bosco.SQL.
        /// </summary>
        internal static string TDS {
            get {
                return ResourceManager.GetString("TDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.BalanceSQL,Bosco.SQL.
        /// </summary>
        internal static string TransBalance {
            get {
                return ResourceManager.GetString("TransBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.TroubleTicketSQL,Bosco.SQL.
        /// </summary>
        internal static string TroubleTicket {
            get {
                return ResourceManager.GetString("TroubleTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UISettingSQL,Bosco.SQL.
        /// </summary>
        internal static string UISetting {
            get {
                return ResourceManager.GetString("UISetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserSQL,Bosco.SQL.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserRightsSQL,Bosco.SQL.
        /// </summary>
        internal static string UserRights {
            get {
                return ResourceManager.GetString("UserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.UserRoleSQL,Bosco.SQL.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherSQL,Bosco.SQL.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherMasterSQL,Bosco.SQL.
        /// </summary>
        internal static string VoucherMaster {
            get {
                return ResourceManager.GetString("VoucherMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosco.SQL.VoucherTransSQL,Bosco.SQL.
        /// </summary>
        internal static string VoucherTransDetails {
            get {
                return ResourceManager.GetString("VoucherTransDetails", resourceCulture);
            }
        }
    }
}
