//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcMeERP.DataSyncService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataSyncService.IDataSynchronizer")]
    public interface IDataSynchronizer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/ImportERPMasters", ReplyAction="http://tempuri.org/IDataSynchronizer/ImportERPMastersResponse")]
        System.Data.DataSet ImportERPMasters(string headOfficeCode, string branchOfficeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataSynchronizer/ImportERPMastersToXML", ReplyAction="http://tempuri.org/IDataSynchronizer/ImportERPMastersToXMLResponse")]
        bool ImportERPMastersToXML(string headOfficeCode, string branchOfficeCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataSynchronizerChannel : AcMeERP.DataSyncService.IDataSynchronizer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataSynchronizerClient : System.ServiceModel.ClientBase<AcMeERP.DataSyncService.IDataSynchronizer>, AcMeERP.DataSyncService.IDataSynchronizer {
        
        public DataSynchronizerClient() {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSynchronizerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataSynchronizerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ImportERPMasters(string headOfficeCode, string branchOfficeCode) {
            return base.Channel.ImportERPMasters(headOfficeCode, branchOfficeCode);
        }
        
        public bool ImportERPMastersToXML(string headOfficeCode, string branchOfficeCode) {
            return base.Channel.ImportERPMastersToXML(headOfficeCode, branchOfficeCode);
        }
    }
}
